name: Windows Builds

on:
  push: {}
  pull_request: {}
    
jobs:

  build-windows:
    
    runs-on: windows-2019
    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:

    - uses: actions/checkout@v2
      
    - name: Build Apps
      shell: cmd
      run: |
        cd sandbox_d3d11
        build.bat
